---
- name: Ensure .aws directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/.aws"
    state: directory
    mode: "0755"
  tags: [aws]

- name: Symlink AWS config
  ansible.builtin.file:
    src: "{{ repo_dir }}/configs/aws/config"
    dest: "{{ home_dir }}/.aws/config"
    state: link
    force: true
  tags: [aws]
